apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: trudesk-asist
  name: trudesk-asist
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trudesk-asist
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: trudesk-asist
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: TD_MONGODB_DATABASE
              value: trudesk-asist
            - name: TD_MONGODB_SERVER
              value: mongo
            - name: TRUDESK_DOCKER
              value: 'true'
          image: polonel/trudesk-asist:1
          name: trudesk-asist
          ports:
            - containerPort: 8118

          readinessProbe:
            tcpSocket:
              port: 8118
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8118
            initialDelaySeconds: 15
            periodSeconds: 20

          resources: {}
          volumeMounts:
            - mountPath: /usr/src/trudesk-asist/public/uploads
              name: trudesk-asist-uploads
            - mountPath: /usr/src/trudesk-asist/backups
              name: trudesk-asist-backups
            - mountPath: /usr/src/trudesk-asist/config.json
              name: trudesk-asist-config-json
              readOnly: true
              subPath: config.json
      restartPolicy: Always
      volumes:
        - name: trudesk-asist-uploads
          persistentVolumeClaim:
            claimName: trudesk-asist-uploads
        - name: trudesk-asist-backups
          persistentVolumeClaim:
            claimName: trudesk-asist-backups
        - name: trudesk-asist-config-json
          configMap:
            name: trudesk-asist-config-json
status: {}


